name: Bug Report
description: Report a bug in DyberVPN
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure DyberVPN with...
        2. Run command...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Operating Mode
      options:
        - hybrid (default)
        - pqonly
        - classic
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: DyberVPN Version
      description: Output of `dybervpn version`
      placeholder: "DyberVPN 0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux (Ubuntu)
        - Linux (Debian)
        - Linux (Fedora)
        - Linux (RHEL/CentOS)
        - Linux (Arch)
        - Linux (Other)
        - macOS
        - Docker
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: "Ubuntu 24.04"

  - type: textarea
    id: config
    attributes:
      label: Configuration (sanitized)
      description: Relevant configuration (remove private keys!)
      render: toml

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (run with `-v` for verbose)
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
